### ISSUE TITLE
Error when building master block simple_ethercat_master_dc

### ISSUE THREAD

**Issue by BENILLICH** [iwoodsawyer/soem_desktop_block#1]
Hello,

I get the error below when building the master block in simple_ethercat_master_dc.
Note that I had to copy some files to the folder of this Simulink file in order to get no errors in the libraries (Packet64.lib and wpcap64.lib from SOEM\oshw\win32\wpcap\Lib\x64 (needed to add 64 to the filename) and WinMM.Lib and WS2_32.Lib from C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64). 

ERROR:
In file included from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:11:0:
SOEM\osal\win32/inttypes.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^~~~~
In file included from SOEM\osal\win32/inttypes.h:43:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:11:
SOEM\osal\win32/stdint.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^~~~~
In file included from SOEM\osal/osal.h:15:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/stdint.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^~~~~
In file included from SOEM\osal/osal.h:14:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/osal_defs.h:24:31: error: unknown type name 'pack'
 #define PACKED_BEGIN __pragma(pack(push, 1))
                               ^
SOEM\soem/ethercattype.h:90:1: note: in expansion of macro 'PACKED_BEGIN'
 PACKED_BEGIN
 ^~~~~~~~~~~~
In file included from SOEM\soem/ethercat.h:14:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
SOEM\soem/ethercattype.h:99:3: warning: data definition has no type or storage class
 } ec_etherheadert;
   ^~~~~~~~~~~~~~~
SOEM\soem/ethercattype.h:99:3: warning: type defaults to 'int' in declaration of 'ec_etherheadert' [-Wimplicit-int]
In file included from SOEM\osal/osal.h:14:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/osal_defs.h:26:29: error: unknown type name 'pack'
 #define PACKED_END __pragma(pack(pop))
                             ^
SOEM\soem/ethercattype.h:100:1: note: in expansion of macro 'PACKED_END'
 PACKED_END
 ^~~~~~~~~~
In file included from SOEM\soem/ethercat.h:14:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
SOEM\soem/ethercattype.h:123:3: warning: data definition has no type or storage class
 } ec_comt;
   ^~~~~~~
SOEM\soem/ethercattype.h:123:3: warning: type defaults to 'int' in declaration of 'ec_comt' [-Wimplicit-int]
In file included from SOEM\osal/osal.h:14:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/osal_defs.h:26:29: error: unknown type name 'pack'
 #define PACKED_END __pragma(pack(pop))
                             ^
SOEM\soem/ethercattype.h:124:1: note: in expansion of macro 'PACKED_END'
 PACKED_END
 ^~~~~~~~~~
In file included from SOEM\soem/ethercat.h:14:0,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
SOEM\soem/ethercattype.h:152:3: warning: data definition has no type or storage class
 } ec_err;
   ^~~~~~
SOEM\soem/ethercattype.h:152:3: warning: type defaults to 'int' in declaration of 'ec_err' [-Wimplicit-int]
In file included from C:/ProgramData/MATLAB/SupportPackages/R2020a/3P.instrset/mingw_w64.instrset/x86_64-w64-mingw32/include/minwindef.h:163:0,
                 from C:/ProgramData/MATLAB/SupportPackages/R2020a/3P.instrset/mingw_w64.instrset/x86_64-w64-mingw32/include/windef.h:8,
                 from C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um/windows.h:171,
                 from C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um/winsock2.h:53,
                 from SOEM\oshw\win32\wpcap\Include/pcap-stdinc.h:49,
                 from SOEM\oshw\win32\wpcap\Include/pcap/pcap.h:41,
                 from SOEM\oshw\win32\wpcap\Include/pcap.h:45,
                 from SOEM\oshw\win32/nicdrv.h:21,
                 from SOEM\soem/ethercat.h:15,
                 from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um/winnt.h:105:25: fatal error: kernelspecs.h: No such file or directory
 #include <kernelspecs.h>
                         ^
compilation terminated.

How can I solve this error and did I need to copy the files?
Thanks!

**Comment by iwoodsawyer** [comment]
You have to use Microsoft Visual Studio C++ compiler with Windows SDK. The free community 2019 or 2017 version works fine. Mingw compiler is not supported yet.

________________________________
From: BENILLICH ***@***.***>
Sent: Monday, May 10, 2021 2:25:39 AM
To: iwoodsawyer/soem_desktop_block ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iwoodsawyer/soem_desktop_block] Error when building master block simple_ethercat_master_dc (#1)


Hello,

I get the error below when building the master block in simple_ethercat_master_dc.
Note that I had to copy some files to the folder of this Simulink file in order to get no errors in the libraries (Packet64.lib and wpcap64.lib from SOEM\oshw\win32\wpcap\Lib\x64 (needed to add 64 to the filename) and WinMM.Lib and WS2_32.Lib from C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64).

ERROR:
In file included from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:11:0:
SOEM\osal\win32/inttypes.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
#error "Use this header only with Microsoft Visual C++ compilers!"
^~~~~
In file included from SOEM\osal\win32/inttypes.h:43:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:11:
SOEM\osal\win32/stdint.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
#error "Use this header only with Microsoft Visual C++ compilers!"
^~~~~
In file included from SOEM\osal/osal.h:15:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/stdint.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
#error "Use this header only with Microsoft Visual C++ compilers!"
^~~~~
In file included from SOEM\osal/osal.h:14:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/osal_defs.h:24:31: error: unknown type name 'pack'
#define PACKED_BEGIN __pragma(pack(push, 1))
^
SOEM\soem/ethercattype.h:90:1: note: in expansion of macro 'PACKED_BEGIN'
PACKED_BEGIN
^~~~~~~~~~~~
In file included from SOEM\soem/ethercat.h:14:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
SOEM\soem/ethercattype.h:99:3: warning: data definition has no type or storage class
} ec_etherheadert;
^~~~~~~~~~~~~~~
SOEM\soem/ethercattype.h:99:3: warning: type defaults to 'int' in declaration of 'ec_etherheadert' [-Wimplicit-int]
In file included from SOEM\osal/osal.h:14:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/osal_defs.h:26:29: error: unknown type name 'pack'
#define PACKED_END __pragma(pack(pop))
^
SOEM\soem/ethercattype.h💯1: note: in expansion of macro 'PACKED_END'
PACKED_END
^~~~~~~~~~
In file included from SOEM\soem/ethercat.h:14:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
SOEM\soem/ethercattype.h:123:3: warning: data definition has no type or storage class
} ec_comt;
^~~~~~~
SOEM\soem/ethercattype.h:123:3: warning: type defaults to 'int' in declaration of 'ec_comt' [-Wimplicit-int]
In file included from SOEM\osal/osal.h:14:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:16:
SOEM\osal\win32/osal_defs.h:26:29: error: unknown type name 'pack'
#define PACKED_END __pragma(pack(pop))
^
SOEM\soem/ethercattype.h:124:1: note: in expansion of macro 'PACKED_END'
PACKED_END
^~~~~~~~~~
In file included from SOEM\soem/ethercat.h:14:0,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
SOEM\soem/ethercattype.h:152:3: warning: data definition has no type or storage class
} ec_err;
^~~~~~
SOEM\soem/ethercattype.h:152:3: warning: type defaults to 'int' in declaration of 'ec_err' [-Wimplicit-int]
In file included from C:/ProgramData/MATLAB/SupportPackages/R2020a/3P.instrset/mingw_w64.instrset/x86_64-w64-mingw32/include/minwindef.h:163:0,
from C:/ProgramData/MATLAB/SupportPackages/R2020a/3P.instrset/mingw_w64.instrset/x86_64-w64-mingw32/include/windef.h:8,
from C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um/windows.h:171,
from C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um/winsock2.h:53,
from SOEM\oshw\win32\wpcap\Include/pcap-stdinc.h:49,
from SOEM\oshw\win32\wpcap\Include/pcap/pcap.h:41,
from SOEM\oshw\win32\wpcap\Include/pcap.h:45,
from SOEM\oshw\win32/nicdrv.h:21,
from SOEM\soem/ethercat.h:15,
from C:\Users\20174748\Documents\School\BEP\New folder\SOEM_desktop_wrapper.c:17:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um/winnt.h:105:25: fatal error: kernelspecs.h: No such file or directory
#include <kernelspecs.h>
^
compilation terminated.

How can I solve this error and did I need to copy the files?
Thanks!
